### ISSUE TITLE
add deprecated licenses

### ISSUE THREAD

**Issue by mojoaxel** [jslicense/spdx-copyleft.json#1]
A lot of projects are still using [deprecated licenses](https://spdx.org/licenses/).
It would be very helpful to add them to this collection for compatibility.

```txt
AGPL-1.0
AGPL-3.0
GFDL-1.1
GFDL-1.2
GFDL-1.3
GPL-1.0
GPL-1.0+
GPL-2.0
GPL-2.0+
GPL-2.0-with-autoconf-exception
GPL-2.0-with-bison-exception
GPL-2.0-with-classpath-exception
GPL-2.0-with-font-exception
GPL-2.0-with-GCC-exception
GPL-3.0
GPL-3.0+
GPL-3.0-with-autoconf-exception
GPL-3.0-with-GCC-exception
LGPL-2.0
LGPL-2.0+
LGPL-2.1
LGPL-2.1+
LGPL-3.0
LGPL-3.0+
```

**Comment by kemitchell** [comment]
How are you consuming this data package? Many tools couple with `spdx-correct` or `npm-license-corrections` to translate deprecated to modern identifiers. Tools like `licensee` reject all licenses by default, unless they're specifically approved.

**Comment by mojoaxel** [comment]
I'm working on adding a copyleft-check to `license-checker`. My approach was to directly compare licenses, but I'll look into 'spdx-correct'. 👍
Thanks for the fast and helpfull reply!

**Comment by kemitchell** [comment]
The `-or-later` fandango at SPDX was, as far as I know, limited to the GPLs.

You might also have a look at https://github.com/blueoakcouncil/blue-oak-copyleft-npm-package
